version: '3'

services:
  nginx:
    image: nginx:latest
    volumes:
      - ./templates:/etc/nginx/templates
      - ./nginx.conf:/etc/nginx/nginx.conf
    ports:
      - "8080:8080"
    environment:
      - NGINX_HOST=quipo-maravilla.com
      - NGINX_PORT=8080
    networks:
      proyecto-aaron:
        ipv4_address: 172.20.0.2
  xampp:
    image: tomsik68/xampp
    volumes:
      - ./crud:/opt/lampp/htdocs
    environment:
      TZ: UTC
    ports:
      - "80:80"
      - "443:443"
    networks:
      proyecto-aaron:
        ipv4_address: 172.20.0.3
  db:
    image: mysql:latest
    volumes:
      - "./mysql/data:/var/lib/mysql"
      - "./mysql/dump:/docker-entrypoint-initdb.d"
    ports:
      - "3306:3306"
    environment:
      TZ: UTC
      MYSQL_USER: user
      MSQL_ROOT_PASSWORD: r00t_p4ssw0rd
      MYSQL_DATABASE: db
    networks:
      proyecto-aaron:
        ipv4_address: 172.20.0.4

networks:
  proyecto-aaron:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: "172.20.0.1/24"


