version: '3'

services:
  nginx:
    image: nginx:latest
    volumes:
      - ./default.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "80:80"
    environment:
      - NGINX_HOST=quipo-maravilla.com
      - NGINX_PORT=80
    networks:
      proyecto-aaron:
        ipv4_address: 172.20.0.2
  xampp:
    image: tomsik68/xampp
    volumes:
      - ./crud:/opt/lampp/htdocs
    environment:
      TZ: UTC
    networks:
      proyecto-aaron:
        ipv4_address: 172.20.0.3
  db:
    image: mysql:latest
    volumes:
      - "./mysql/data:/var/lib/mysql"
      - "./start.sql:/docker-entrypoint-initdb.d/setup.sql"
    environment:
      TZ: UTC
      MYSQL_ROOT_PASSWORD: r00t_p4ssw0rd
      MYSQL_DATABASE: db
      MYSQL_ROOT_HOST: '%'
    networks:
      proyecto-aaron:
        ipv4_address: 172.20.0.4

networks:
  proyecto-aaron:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: "172.20.0.1/24"
